drives:
  - {container: cephosd1, drive: xvdb1, partition: /dev/xvdb1}
  - {container: cephosd2, drive: xvdb2, partition: /dev/xvdb2}
  - {container: cephosd3, drive: xvdb3, partition: /dev/xvdb3}

data_volume: /dev/xvdb
