---

- hosts: cephosd1,cephosd2,cephosd3
  vars_files:
    - AIO_user_config.yml
  tasks:
    - name: remove ceph_fsid
      file:
        path: /mnt/xfsdisk/ceph_fsid
        state: absent

- hosts: cephadmin
  vars_files:
    - AIO_user_config.yml
  tasks:
    - name: purge ceph
      shell: ceph-deploy purge cephadmin cephmon cephrgw1 cephrgw2 cephosd1 cephosd2 cephosd3
    - name: purge ceph data
      shell: ceph-deploy purgedata cephadmin cephmon cephrgw1 cephrgw2 cephosd1 cephosd2 cephosd3
    - name: remove ceph keys
      shell: ceph-deploy forgetkeys

- hosts: physical_host
  vars_files:
    - AIO_user_config.yml
  roles:
    - teardown


